### ISSUE TITLE
About depthwise-conv

### ISSUE THREAD

**Issue by WangWalter** [jshilong/FisherPruning#1]
Hi,
I have DepthWise Conv layer in my network. And It is not detected in self.conv2ancest. 
Do the project support DepthWise convolution ?

Thanks.

**Comment by jshilong** [comment]
In the initial version, we support GroupConv. It doesn’t need conv2ancest to identify it. It can be identified based on `groups` of `Conv2d`. However, because I am involved in another project now, I don’t have enough time to refactor code related to GroupConv and two-stage models for the time being. If you need it urgently, you can refer to the description in the paper and implement it by yourself.

**Comment by chuong98** [comment]
@jshilong Can you elaborate this:

> It doesn’t need conv2ancest to identify it. It can be identified based on groups of Conv2d

**Comment by tu12306** [comment]
> In the initial version, we support GroupConv. It doesn’t need conv2ancest to identify it. It can be identified based on `groups` of `Conv2d`. However, because I am involved in another project now, I don’t have enough time to refactor code related to GroupConv and two-stage models for the time being. If you need it urgently, you can refer to the description in the paper and implement it by yourself.

Can you provide GConv and DW Conv related codes recently?
