### ISSUE TITLE
Release of classification code&model

### ISSUE THREAD

**Issue by Ben-Louis** [jshilong/FisherPruning#2]
Hello, may I ask when will u release the code and models for classification task? 
Thanks

**Comment by jshilong** [comment]
The code related to classification is based on an Internal classification codebase instead of MMClassification, and the code related to GroupConv and faster-RCNN is a little complicated so I did not release them in the initial version. However, I was involved in some heavily refactoring of MMDetection and OpenMMlab after ICML and did not have enough time to refactor the code to MMClassification, but this hook can prune the ResNet and other models without GN after minor modification when you apply it to MMClassifaction. You can try it if you urgently need it
